### ISSUE TITLE
 ThemeManager.Initialize cause Microsoft.CSharp.RuntimeBinder.RuntimeBinderException on Win10 22H2

### ISSUE THREAD

**Issue by IShiraiKurokoI** [WinUICommunity/Common#4]
I use the following code to initialize theme option of mainwindow
```
m_window = new MainWindow();
themeManager = ThemeManager.Initialize(m_window, new ThemeOptions
{
    BackdropType = BackdropType.DesktopAcrylic,
    ElementTheme = SettingsTheme,
    TitleBarCustomization = new TitleBarCustomization
    {
            TitleBarType = TitleBarType.AppWindow
    }
}); 
```
It works all fine on windows11, but on windows10 22H2 with latest appruntime, it cause RuntimeBinderException 
stacktrace below
```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'Windows.UI.Color?' to 'Microsoft.UI.Xaml.Media.Brush'
   at CallSite.Target(Closure , CallSite , Object , Nullable`1 )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at WinUICommunity.ThemeManager.SetBackdropFallBackColorForWindows10(Window window)
   at WinUICommunity.ThemeManager.InternalInitialize(Window window, ThemeOptions themeOptions)
   at WinUICommunity.ThemeManager..ctor(Window window, ThemeOptions themeOptions)
   at WinUICommunity.ThemeManager.Initialize(Window window, ThemeOptions themeOptions)
   at myapp.App.OnLaunched(LaunchActivatedEventArgs e)
```

**Comment by ghost1372** [comment]
Tnx for report i will fix this issue soon
